-- =============================================================================
-- Migration 023: Master Database Reconciliation (NO-OP PLACEHOLDER)
-- =============================================================================
--
-- The reconciliation logic for this migration was intentionally embedded into
-- master-migration.sql so that it executes on EVERY system startup, and
-- critically, BEFORE the numbered migration sequence (017, 018, ..., 022).
--
-- Execution order in migration-runner.ts:
--   ① Programmatic columnsToSync loop
--   ② master-migration.sql  ← reconciliation happens HERE (Phases A-G)
--   ③ 017_sync_category_ids.sql
--   ④ 018_aggressive_uuid_to_varchar.sql
--   ⑤ 019_add_sub_account_logic.sql
--   ⑥ 020_add_missing_description_columns.sql
--   ⑦ 021_create_purchase_return_items.sql
--   ⑧ 022_add_currencies_and_exchange_rates.sql
--   ⑨ THIS FILE (no-op — just records migration was applied)
--
-- This ensures old production databases are fully repaired before any of
-- migrations 017-022 attempt to execute, preventing foreign key violations,
-- missing-column errors, and UUID/VARCHAR type conflicts.
--
-- Do NOT add any SQL logic back here. Edit master-migration.sql instead.
-- =============================================================================

-- Intentional no-op. Record kept for migration history tracking only.
SELECT 1;
