export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan', nameAr: 'أفغانستان', flag: '🇦🇫' },
  { code: 'AL', name: 'Albania', nameAr: 'ألبانيا', flag: '🇦🇱' },
  { code: 'DZ', name: 'Algeria', nameAr: 'الجزائر', flag: '🇩🇿' },
  { code: 'AS', name: 'American Samoa', nameAr: 'ساموا الأمريكية', flag: '🇦🇸' },
  { code: 'AD', name: 'Andorra', nameAr: 'أندورا', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', nameAr: 'أنغولا', flag: '🇦🇴' },
  { code: 'AR', name: 'Argentina', nameAr: 'الأرجنتين', flag: '🇦🇷' },
  { code: 'AM', name: 'Armenia', nameAr: 'أرمينيا', flag: '🇦🇲' },
  { code: 'AU', name: 'Australia', nameAr: 'أستراليا', flag: '🇦🇺' },
  { code: 'AT', name: 'Austria', nameAr: 'النمسا', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaijan', nameAr: 'أذربيجان', flag: '🇦🇿' },
  { code: 'BH', name: 'Bahrain', nameAr: 'البحرين', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh', nameAr: 'بنجلاديش', flag: '🇧🇩' },
  { code: 'BE', name: 'Belgium', nameAr: 'بلجيكا', flag: '🇧🇪' },
  { code: 'BR', name: 'Brazil', nameAr: 'البرازيل', flag: '🇧🇷' },
  { code: 'CA', name: 'Canada', nameAr: 'كندا', flag: '🇨🇦' },
  { code: 'CN', name: 'China', nameAr: 'الصين', flag: '🇨🇳' },
  { code: 'EG', name: 'Egypt', nameAr: 'مصر', flag: '🇪🇬' },
  { code: 'FR', name: 'France', nameAr: 'فرنسا', flag: '🇫🇷' },
  { code: 'DE', name: 'Germany', nameAr: 'ألمانيا', flag: '🇩🇪' },
  { code: 'IN', name: 'India', nameAr: 'الهند', flag: '🇮🇳' },
  { code: 'IQ', name: 'Iraq', nameAr: 'العراق', flag: '🇮🇶' },
  { code: 'IT', name: 'Italy', nameAr: 'إيطاليا', flag: '🇮🇹' },
  { code: 'JP', name: 'Japan', nameAr: 'اليابان', flag: '🇯🇵' },
  { code: 'JO', name: 'Jordan', nameAr: 'الأردن', flag: '🇯🇴' },
  { code: 'KW', name: 'Kuwait', nameAr: 'الكويت', flag: '🇰🇼' },
  { code: 'LB', name: 'Lebanon', nameAr: 'لبنان', flag: '🇱🇧' },
  { code: 'LY', name: 'Libya', nameAr: 'ليبيا', flag: '🇱🇾' },
  { code: 'MA', name: 'Morocco', nameAr: 'المغرب', flag: '🇲🇦' },
  { code: 'OM', name: 'Oman', nameAr: 'عمان', flag: '🇴🇲' },
  { code: 'PS', name: 'Palestine', nameAr: 'فلسطين', flag: '🇵🇸' },
  { code: 'QA', name: 'Qatar', nameAr: 'قطر', flag: '🇶🇦' },
  { code: 'SA', name: 'Saudi Arabia', nameAr: 'السعودية', flag: '🇸🇦' },
  { code: 'SD', name: 'Sudan', nameAr: 'السودان', flag: '🇸🇩' },
  { code: 'SY', name: 'Syria', nameAr: 'سوريا', flag: '🇸🇾' },
  { code: 'TN', name: 'Tunisia', nameAr: 'تونس', flag: '🇹🇳' },
  { code: 'TR', name: 'Turkey', nameAr: 'تركيا', flag: '🇹🇷' },
  { code: 'AE', name: 'United Arab Emirates', nameAr: 'الإمارات', flag: '🇦🇪' },
  { code: 'GB', name: 'United Kingdom', nameAr: 'المملكة المتحدة', flag: '🇬🇧' },
  { code: 'US', name: 'United States', nameAr: 'الولايات المتحدة', flag: '🇺🇸' },
  { code: 'YE', name: 'Yemen', nameAr: 'اليمن', flag: '🇾🇪' },
];

export const CURRENCIES = [
  { code: 'EGP', symbol: 'ج.م', name: 'Egyptian Pound', nameAr: 'جنيه مصري', flag: '🇪🇬' },
  { code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal', nameAr: 'ريال سعودي', flag: '🇸🇦' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', nameAr: 'درهم إماراتي', flag: '🇦🇪' },
  { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', nameAr: 'دينار كويتي', flag: '🇰🇼' },
  { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal', nameAr: 'ريال قطري', flag: '🇶🇦' },
  { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial', nameAr: 'ريال عماني', flag: '🇴🇲' },
  { code: 'BHD', symbol: 'د.ب', name: 'Bahraini Dinar', nameAr: 'دينار بحريني', flag: '🇧🇭' },
  { code: 'USD', symbol: '$', name: 'US Dollar', nameAr: 'دولار أمريكي', flag: '🇺🇸' },
  { code: 'EUR', symbol: '€', name: 'Euro', nameAr: 'يورو', flag: '🇪🇺' },
  { code: 'GBP', symbol: '£', name: 'British Pound', nameAr: 'جنيه إسترليني', flag: '🇬🇧' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira', nameAr: 'ليرة تركية', flag: '🇹🇷' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen', nameAr: 'ين ياباني', flag: '🇯🇵' },
];

export const MONTHS = [
  { value: 1, name: 'January', nameAr: 'يناير' },
  { value: 2, name: 'February', nameAr: 'فبراير' },
  { value: 3, name: 'March', nameAr: 'مارس' },
  { value: 4, name: 'April', nameAr: 'أبريل' },
  { value: 5, name: 'May', nameAr: 'مايو' },
  { value: 6, name: 'June', nameAr: 'يونيو' },
  { value: 7, name: 'July', nameAr: 'يوليو' },
  { value: 8, name: 'August', nameAr: 'أغسطس' },
  { value: 9, name: 'September', nameAr: 'سبتمبر' },
  { value: 10, name: 'October', nameAr: 'أكتوبر' },
  { value: 11, name: 'November', nameAr: 'نوفمبر' },
  { value: 12, name: 'December', nameAr: 'ديسمبر' },
];
